### ISSUE TITLE
Improve or remove shield

### ISSUE THREAD

**Issue by lionleaf** [ninjadev/globalgamejam2016#130]
Not too happy with how shields work at the moment:

Spammed all the time, and aimed correctly they absorb a LOT even with low energy. easyfix: remove. Or fix collision to match visuals as well as making it so that you're not using it that often (longer recharge time? disabled after depleted for a while?)

In any case, shields would work a lot better with proper latency mitigation, quick reflex skill dodges with high latency is maybe not so fun?

**Comment by iver56** [comment]
Some easy quick fixes that would solve some of the issues:
- [x] Move the shield closer to the body, making it look more like the shield actually stops the bullets
- [x] Add sound effect that plays when the shield takes a hit, making it obvious that the shield works
- [x] Tweak recharge parameters: for example x^2 recharging instead of x, making the shield recharge slowly when it is in a bad/depleted state
